sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune 
before_install:
  - "npm install -g npm@latest"  
script:
  - npm run test:single
after_success:
  - npm run semantic-release
